name: invokeai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip=22.2.2
  - numpy=1.23.3
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pytorch=1.12.1
  - cudatoolkit=11.6
  - pip:
    - accelerate~=0.13
    - albumentations==0.4.3
    - diffusers[torch]~=0.11
    - einops==0.3.0
    - eventlet
    - flask==2.1.3
    - flask_cors==3.0.10
    - flask_socketio==5.3.0
    - getpass_asterisk
    - huggingface-hub>=0.11.1
    - imageio-ffmpeg==0.4.2
    - imageio==2.9.0
    - kornia==0.6.0
    - omegaconf==2.2.3
    - opencv-python==4.5.5.64
    - picklescan
    - pillow==9.2.0
    - pudb==2019.2
    - pyreadline3
    - pytorch-lightning==1.7.7
    - realesrgan
    - requests==2.25.1
    - safetensors~=0.2
    - send2trash==1.8.0
    - streamlit==1.12.0
    - taming-transformers-rom1504
    - test-tube>=0.7.5
    - torch-fidelity==0.3.0
    - torchmetrics==0.7.0
    - transformers~=4.25
    - git+https://github.com/openai/CLIP.git@main#egg=clip
    - git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k-diffusion
    - git+https://github.com/invoke-ai/clipseg.git@relaxed-python-requirement#egg=clipseg
    - git+https://github.com/invoke-ai/GFPGAN@basicsr-1.4.2#egg=gfpgan
    - git+https://github.com/invoke-ai/PyPatchMatch@0.1.5#egg=pypatchmatch
    - -e .
